chore/form
naveteam/react-native-nave-typescript pull request #11
Opened 2021-05-17 18:41 UTC by lucasGabrielDeAA

- Adição das libs `react-hook-form` e `yup` para manipulação e validação de formulários;
- Correção visuais no componente de Botão;
- Criação do componente de Input;
- Criação de uma segunda tela apenas com o comportamento do formulário, para testes

`Testando:` 
1. Instale as dependências com `yarn && yarn pod-install`
2. Re-compile o app com `yarn android` ou `yarn ios`
3. Acesse a tela do formulário e teste seu comportamento

2021-05-18 18:05 UTC, GuiWM approved these changes

2021-05-24 15:38 UTC, powilliam requested changes
Tá bem daora, só tem que dar uma olhada naquele bug do valor do input estar resetando no form. Dei uma debugada rápida, isso acontece sempre que algum state muda, mais exatamente aquele `isPasswordInput` na tela do `Form`. Tecnicamente isso tá relacionado com a diferença entre os `Uncontrolled Components` (que é o caso de forms com essa e outras libs) e `Controlled Components`. Talvez se esse `setState` fosse interno do componente `Input` isso não aconteceria, não tenho certeza.

2021-05-26 00:17 UTC, powilliam commented on template/src/screens/Form/Form.tsx
> +            secureTextEntry
Aquele bug do campo resetar continua, debuguei e o responsável é esse carinha. Não cheguei a ir muito atrás de issues relacionadas a isso, mas levando em conta que é uma prop, faz sentido ela causar re-renders no compontente de `Input`

2021-05-26 11:21 UTC, lucasGabrielDeAA commented on template/src/screens/Form/Form.tsx
> +            secureTextEntry
> Aquele bug do campo resetar continua, debuguei e o responsável é esse carinha. Não cheguei a ir muito atrás de issues relacionadas a isso, mas levando em conta que é uma prop, faz sentido ela causar re-renders no compontente de `Input`. Se não encontrarmos solução p isso, o que tu acha de usarmos máscara de input para ocultar a senha? Acho que talvez funcionaria, mas em contrapartida, iriamos perder a UX do input nativo, onde sempre a última letra da senha fica visível por alguns segundos e depois desaparece.

Cara, não vejo sentido em utilizarmos máscara no input para isso, seu uso não é para isso, até porque a prop `secureTextEntry` já é do próprio input do react-native.

2021-05-26 11:44 UTC, powilliam approved these changes

2021-05-26 11:44 UTC, lucasGabrielDeAA commented on template/src/screens/Form/Form.tsx
> +            secureTextEntry
`DISCLAIMER` o comportamento de reset do input com a prop `secureTextEntry` é padrão. O mesmo foi testado e validado com o `TextInput` do próprio **react-native** sem qualquer uso do **react-hook-form** e se mostrou da mesma forma

2021-05-26 11:45 UTC, merged