Feat/storybook v2
naveteam/react-native-nave-typescript pull request #19
Opened 2021-06-07 13:24 UTC by GuiWM

Configurado storybook.

Para testar:
- Instale as dependências através do yarn.
- Caso o teste seja efetuado no ambiente IOS, rode yarn pod-install.
- Mude o export default do arquivo app-module.tsx para export { default } from '../storybook';
- Rode yarn ios e navegue pela interface do storybook.

2021-06-07 13:38 UTC, lucasGabrielDeAA requested changes

2021-06-07 13:38 UTC, lucasGabrielDeAA commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
Algum motivo específico para a mudança do import do `useTheme`? Pois, por padrão o que utilizamos é o da **@react-navigation/navite**

2021-06-07 13:48 UTC, GuiWM commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
Quando utilizado o @react-navigation/native, o tema que é pego é o do storybook, dai as cores ficam erradas.

2021-06-07 16:25 UTC, lucasGabrielDeAA commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
Como assim erradas? No caso, bastaria setar então o tema certo lá no `ThemeProvider` no arquivo app-module.txs então, não?

2021-06-07 16:53 UTC, julianoddreis commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
Acho que no nosso caso, que usamos styled-components, o certo é ter os 2 theme providers no app, o que vcs acham?

2021-06-07 16:55 UTC, julianoddreis commented on template/storybook/preview.js
> +console.log('eae');
remover console

2021-06-07 16:58 UTC, julianoddreis commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
ahhh, agora que vi, já tem os 2 providers no app. De repente falta o provider do navigation lá no storybook então

2021-06-07 17:14 UTC, powilliam commented on template/storybook/preview.js
> +console.log('eae');
muito bom esse console

eae

2021-06-07 17:34 UTC, powilliam commented
Que parada dahora, não sabia que tinha isso pra mobile

2021-06-07 17:35 UTC, powilliam approved these changes

2021-06-07 17:38 UTC, lucasGabrielDeAA commented on template/src/components/Button/Button.tsx
> +import styled, { useTheme } from 'styled-components/native';
Pois é, acho que a saída pode ser esta mesmo de termos os dois providers lá no storybook. Que daí não rolaria o fato de "cores erradas"

2021-06-08 13:03 UTC, lucasGabrielDeAA approved these changes

2021-06-08 14:13 UTC, julianoddreis approved these changes

2021-06-08 14:33 UTC, merged