feat: created modal component
naveteam/react-native-nave-typescript pull request #24
Opened 2021-06-14 13:37 UTC by GuiWM

Criado componente de modal. 
Para testar:

- Rodar o projeto com yarn ios/android.
- Fazer o import do componente na tela Home.
- Passar propriedades de handleClose e open com manipulação de estado, além de 'children' como conteúdo.
- Testar funcionamento.

2021-06-14 13:44 UTC, lucasGabrielDeAA requested changes

2021-06-14 13:44 UTC, lucasGabrielDeAA commented on template/src/components/Modal/Modal.tsx
> +import { ColumnProps, Column } from '../Column';
pode fazer o import de `src/components`

2021-06-14 13:44 UTC, lucasGabrielDeAA commented on template/src/components/Modal/Modal.tsx
> +  handleClose: Function;
a prop **handleClose** pode ser alterada para a seguinte forma
`handleClose?(): void`

2021-06-14 14:20 UTC, GuiWM commented on template/src/components/Modal/Modal.tsx
> +import { ColumnProps, Column } from '../Column';
Se eu fizer o import assim dá um warning: Require cycle: src/components/index.ts ->

2021-06-14 14:20 UTC, GuiWM commented on template/src/components/Modal/Modal.tsx
> +  handleClose: Function;
Beleza! Tem algum motivo especifico?

2021-06-14 17:39 UTC, lucasGabrielDeAA commented on template/src/components/Modal/Modal.tsx
> +import { ColumnProps, Column } from '../Column';
Ahh sim, entendi. Então nesse caso pode desconsiderar

2021-06-14 17:40 UTC, lucasGabrielDeAA commented on template/src/components/Modal/Modal.tsx
> +  handleClose: Function;
o tipo Function tem sido depreciado no uso com o typescript, o (): alguma_coisa permite a tipagem da própria função como dos parâmetros quando existirem.

2021-06-15 11:27 UTC, lucasGabrielDeAA approved these changes

2021-06-15 11:42 UTC, powilliam commented on template/src/components/Modal/Modal.tsx
> +const ModalComponent: FC<ModalComponentProps> = ({
Consegue dale aquele teste de componente pra ele?. Eu posso te ajudar a fazer isso caso quiser

2021-06-15 11:56 UTC, powilliam commented on template/src/components/Modal/Modal.tsx
> +const ModalComponent: FC<ModalComponentProps> = ({
Ah, pode desconsiderar. Eu fiz uns setups no ambiente de teste, no outro pr, que tu iria precisar

2021-06-15 11:56 UTC, powilliam approved these changes

2021-06-15 11:57 UTC, merged