chore/readme
naveteam/react-native-nave-typescript pull request #3
Opened 2021-05-12 18:08 UTC by lucasGabrielDeAA

Atualização do arquivo **README.md** com o passo a passo para clonar o repositório, executar a aplicação e testar a mesma. Juntamente com alterações no arquivo **.gitignore**

2021-05-12 20:51 UTC, powilliam approved these changes

2021-05-13 12:58 UTC, gabrieldocoutos requested changes

2021-05-13 12:58 UTC, gabrieldocoutos commented on README.md
> +yarn android | ios
não achei isso aqui tão claro, poderia ser mais explícito como: `yarn android` or `yarn ios`

2021-05-13 12:58 UTC, gabrieldocoutos commented on README.md
>  Copyright 2019 nave.rs
2019? não deveria ser 2021?

2021-05-13 13:03 UTC, lucasGabrielDeAA commented on README.md
> +yarn android | ios
Boa, vou alterar isto

2021-05-13 13:04 UTC, lucasGabrielDeAA commented on README.md
>  Copyright 2019 nave.rs
Está dessa forma pois peguei o mesmo conteúdo do antigo, mas eu altero

2021-05-13 14:12 UTC, gabrieldocoutos approved these changes
LGTM!

2021-05-13 20:29 UTC, merged